name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: target
        key: target-armv7hl-0

    - name: Build armv7hl RPMS
      uses: R1tschY/sailfish-sdk-action@v1
      with:
        arch: 'armv7hl'
        release: '3.4.0.24'
        fix-version: false
        enable-debug: true
        check: true

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: rpm-armv7hl
        path: RPMS